project_id = "gjnnqeqlxxoiajgklevz"

[functions.signup-with-tenant]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = true

[functions.lead-intake]
verify_jwt = false

[functions.export-leads]
verify_jwt = true